# Makefile

# Check if .env exists
ifeq (,$(wildcard .env))
$(error .env file is missing at .env. Please create one based on .env.example)
endif

# Load environment variables from .env
include .env

#################################################################################
## Supabase Commands
#################################################################################

supabase-create: ## Create Supabase database
	@echo "Creating Supabase database..."
	uv run python -m src.infrastructure.supabase.create_db

supabase-delete: ## Delete Supabase database
	@echo "Deleting Supabase database..."
	uv run python -m src.infrastructure.supabase.delete_db

#################################################################################
## Qdrant Commands
#################################################################################

qdrant-create-collection:  ## Create Qdrant collection
	@echo "Creating Qdrant collection..."
	uv run python -m src.infrastructure.qdrant.create_collection

qdrant-delete-collection: ## Delete Qdrant collection
	@echo "Deleting Qdrant collection..."
	uv run python -m src.infrastructure.qdrant.delete_collection

qdrant-create-indexes:  ## Create Qdrant index
	@echo "Updating HNSW and creating Qdrant indexes..."
	uv run python -m src.infrastructure.qdrant.create_indexes

qdrant-ingest-from-sql:
	@echo "Ingesting data from SQL to Qdrant..."
	uv run python -m src.infrastructure.qdrant.ingest_from_sql

#################################################################################
## Prefect Flow Commands
#################################################################################

ingest-rss-article-flow:
	@echo "Running ingest articles flow..."
	uv run python -m src.piplines.qdrant.flows.rss_ingestion_flow
	@echo "Ingest RSS articles flow completed."

ingest-embedding-flow:
	@echo "Running ingest embeddings flow..."
	$(if $(FROM_DATE), \
	uv run python -m src.piplines.qdrant.embeddings_ingestion_flow --from_date $(FROM_DATE),\
	uv run python -m src.piplines.qdrant.embeddings_ingestion_flow)
	@echo "Ingest emebeddings flow completed."